### ISSUE TITLE
Error when running jupyter nbclassic -h

### ISSUE THREAD

**Issue by jtpio** [jupyterlab/nbclassic#30]
Opening an issue related to this PR: https://github.com/jupyterlab/nbclassic/pull/29

Running `jupyter nbclassic -h` throws the following error:

```
[E 2020-09-25 17:56:40.630 NotebookApp] Failed collecting help-message for alias 'transport', due to: 'KernelManager.transport'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/bin/jupyter-nbclassic", line 11, in <module>
    load_entry_point('nbclassic', 'console_scripts', 'jupyter-nbclassic')()
  File "/home/runner/work/nbclassic/jupyter_server/jupyter_server/extension/application.py", line 444, in launch_instance
    _preparse_for_stopping_flags(cls, args)
  File "/home/runner/work/nbclassic/jupyter_server/jupyter_server/extension/application.py", line 69, in _preparse_for_stopping_flags
    app.print_help('--help-all' in interpreted_argv)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 503, in print_help
    print('\n'.join(self.emit_help(classes=classes)))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 514, in emit_help
    for l in self.emit_options_help():
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 463, in emit_options_help
    for l in self.emit_alias_help():
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/traitlets/config/application.py", line 398, in emit_alias_help
    trait = cls.class_traits(config=True)[traitname]
KeyError: 'KernelManager.transport'
```

Example run: https://github.com/jupyterlab/nbclassic/pull/29/checks?check_run_id=1167277492

This seems to be related to the two following aliases:

https://github.com/jupyterlab/nbclassic/blob/cff037e8364005b5693b46e62640bd877c6f1659/nbclassic/notebookapp.py#L91

https://github.com/jupyterlab/nbclassic/blob/cff037e8364005b5693b46e62640bd877c6f1659/nbclassic/notebookapp.py#L97

**Comment by jtpio** [comment]
It was found when adding the conda forge recipe for `nbclassic` here: https://github.com/conda-forge/staged-recipes/pull/12722

However we can probably omit the test that runs `jupyter nbclassic -h` in the recipe (https://github.com/conda-forge/staged-recipes/pull/12722/commits/c168a54c641fe0dbec3bcf1bffde434227fc5016) for now, and keep it as an `nbclassic` issue which can be fixed later (so it's not a blocker for the recipe)

**Comment by Zsailer** [comment]
This seems to be working again (not sure when that happened 😆)

**Comment by jtpio** [comment]
Just rebased https://github.com/jupyterlab/nbclassic/pull/29 to add this command on CI, and it seems to be passing :+1:
