### ISSUE TITLE
Error when using --autoreload

### ISSUE THREAD

**Issue by Carreau** [jupyterlab/nbclassic#39]
```
$ jupyter notebook --no-browser --NotebookApp.autoreload=True
[I 10:55:34.397 NotebookApp] Autoreload enabled: the webapp will restart when any Python src file changes.
[W 10:55:36.217 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/Users/bussonniermatthias/miniconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 1945, in init_server_extensions
        func(self)
      File "/Users/bussonniermatthias/miniconda3/lib/python3.8/site-packages/jupyterlab/serverextension.py", line 13, in load_jupyter_server_extension
        extension.update_config(serverapp.config)
      File "/Users/bussonniermatthias/miniconda3/lib/python3.8/site-packages/nbclassic/shim.py", line 138, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(config)
      File "/Users/bussonniermatthias/miniconda3/lib/python3.8/site-packages/nbclassic/shim.py", line 228, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, autoreload, not found.
```

You may also want to update the setup.py link for homepage to point to github and not Jupyter.org or it can be hard to find this repo.

**Comment by Zsailer** [comment]
Fixed in jupyter-server/jupyter_server#380
